// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zddljywcvqxbouhyryoi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkZGxqeXdjdnF4Ym91aHlyeW9pIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNDc0MjUsImV4cCI6MjA1MjYyMzQyNX0.mPp9rftlfdHApQbSTtgzwAjZhKg0KhK_Uz9QCoC8hcM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);